apps/webpage/urls.py
from django.urls import path
from . import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", views.index, name="index"),
    path("historia/", views.historia, name="historia"),
    path("material_mayor/", views.material_mayor, name="material_mayor"),
    path("voluntarios/", views.voluntarios, name="voluntarios"),
    path("brigada_juvenil/", views.brigada_juvenil, name="brigada_juvenil"),
    path("noticias/", views.noticias, name="noticias"),
    path("contacto/", views.contacto, name="contacto"),
    path("postulacion/", views.postulacion, name="postulacion"),
    path("usuarios/logout", views.login, name="logout" ),
    path('ruta-a-tu-vista-detalle-noticia/<int:noticia_id>/', views.detalle_noticia, name='detalle_noticia'),
    path('cerrar-sesion/', views.cerrar_sesion, name='cerrar_sesion'),
]

if  settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

primera/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("apps.webpage.urls")),
]
if  settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/webpage/models.py
import os, re
from django.db import models
from django.core.exceptions import ValidationError
from django.core.validators import EmailValidator, RegexValidator, MaxLengthValidator, MinLengthValidator, MinValueValidator, MaxValueValidator

# Validaciones
# IMAGEN
def validar_tamano_imagen(value):
    limite = 20 * 1024 * 1024  # 20 MB
    if value.size > limite:
        raise ValidationError('El tamaño del archivo no puede exceder los 20 MB.')
def validar_formato_imagen(value):
    if not value.name.endswith(('.png', '.jpg', '.jpeg')):
        raise ValidationError('El formato del archivo debe ser PNG, JPEG o JPG.')
#TELEFONO
def validar_telefono(value):
    if not re.match(r'^\d{8}$', value):
        raise ValidationError('El número de teléfono debe tener exactamente 8 dígitos y contener solo números.')
#MENSAJE
PALABRAS_INAPROPIADAS = ['Mierda', 'Puta', 'Conchetumare', 'conchetumare', 'Ctm', 'ctm', 'maricon', 'marica']
def validar_mensaje(value):
    # Verifica si contiene palabras inapropiadas
    if any(palabra in value.lower() for palabra in PALABRAS_INAPROPIADAS):
        raise ValidationError('El mensaje contiene lenguaje inapropiado.')

    # Verifica si contiene URLs
    if re.search(r'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*(),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+', value):
        raise ValidationError('El mensaje no debe contener URLs.')
#CORREO
DOMINIOS_PERMITIDOS = ['gmail.com', 'primeracbpa.cl', 'icloud.com', 'cbpa.cl', 'duocuc.cl', 'outlook.es', 'outlook.com', 'outlook.cl']
def validar_dominio_correo(value):
    dominio_email = value.split('@')[-1]
    if dominio_email not in DOMINIOS_PERMITIDOS:
        raise ValidationError('El dominio del correo electrónico no está permitido.')
#PDFS
def validar_formato_pdf(value):
    if not value.name.endswith('.pdf'):
        raise ValidationError('El archivo debe ser un PDF.')
def validar_tamano_pdf(value):
    limite = 20 * 1024 * 1024  # 20 MB
    if value.size > limite:
        raise ValidationError('El tamaño del pdf no puede exceder los 20 MB.')
# Validaciones

class CategoriaNoticia(models.Model):
    CategoriaNoticia = models.CharField(max_length=50, null=True, blank=True, editable=True, verbose_name="Categoría")
    def __str__(self):
        return self.CategoriaNoticia
    class Meta:
        verbose_name = "Noticia - categoría"
        verbose_name_plural = "Noticias - categorías"

class Noticia(models.Model):
    titulo          = models.CharField(max_length=50, null=False, blank=False, default="Título genérico", editable=True, verbose_name="Título")
    fecha_pub       = models.DateTimeField(auto_now_add=True, verbose_name="Fecha")
    imagen_noticia  = models.ImageField(max_length=50, null=True, verbose_name="Imagen", validators=[validar_tamano_imagen,validar_formato_imagen])
    categoria       = models.ForeignKey(CategoriaNoticia, on_delete=models.PROTECT, verbose_name="Categoría")
    def __str__(self):
        return str(self.fecha_pub) + " " + self.titulo
    class Meta:
        verbose_name = "Noticia"
        verbose_name_plural = "Noticias"

class Contenido(models.Model):
    contenido   = models.TextField(null=True, blank=True, editable=True,validators=[MaxLengthValidator(1000),validar_mensaje])
    noticia     = models.ForeignKey(Noticia, on_delete=models.CASCADE)
    def __str__(self):
        return self.contenido
    class Meta:
        verbose_name = "Noticia - contenido"
        verbose_name_plural = "Noticias - contenidos"

class EspecialidadCarro(models.Model):
    especialidad    = models.CharField(max_length=50, null=False, blank=False, editable=True)
    descripcion     = models.CharField(max_length=50, null=True, blank=True, editable=True, default="Ingrese una descripción", verbose_name="Descripción")
    icono           = models.ImageField(max_length=50, null=True, upload_to="Iconos", validators=[validar_formato_imagen,validar_tamano_imagen])
    def __str__(self):
        return self.especialidad
    class Meta:
        verbose_name = "Carro - especialidad"
        verbose_name_plural = "Carros - especialidades"

class CarroBomba(models.Model):
    modelo              = models.CharField(max_length=50, null=False, blank=False, editable=True, default="Carro ...")
    origen              = models.CharField(max_length=50, null=False, blank=False, editable=True, default="Nacional")
    anio_fabricacion    = models.IntegerField(null=False, blank=False, validators=[MinValueValidator(1800), MaxValueValidator(2200)], default=2000, verbose_name="Año de fabricación")
    caracteristicas     = models.CharField(max_length=150, null=True, blank=True, editable=True, default="Ingrese una característica", verbose_name="Características", validators=[validar_mensaje])
    especialidad        = models.ForeignKey(EspecialidadCarro, on_delete=models.PROTECT)
    foto                = models.ImageField(max_length=50, null=False, upload_to="Carros",validators=[validar_formato_imagen,validar_tamano_imagen])
    reliquia            = models.BooleanField(blank=False, null=False)
    def __str__(self):
        return self.modelo
    class Meta:
        verbose_name = "Carro"
        verbose_name_plural = "Carros"

class CargoMiembro(models.Model):
    cargo = models.CharField(max_length=50, unique=True, editable=True, validators=[validar_mensaje])
    def __str__(self):
        return self.cargo
    class Meta:
        verbose_name = "Voluntario - cargo"
        verbose_name_plural = "Voluntarios - cargos"
    
class Miembro(models.Model):
    nombre          = models.CharField(max_length=25, null=False, blank=False, editable=True, validators=[validar_mensaje])
    apellido        = models.CharField(max_length=25, null=False, blank=False, editable=True, validators=[validar_mensaje])
    cargo           = models.ForeignKey(CargoMiembro, on_delete=models.PROTECT)
    foto            = models.ImageField(max_length=50, null=True, blank=True, upload_to="Voluntarios", validators=[validar_formato_imagen,validar_tamano_imagen])
    numero_cargo    = models.IntegerField(null=True, blank=True, default=100, validators=[MinValueValidator(41), MaxValueValidator(1000)], verbose_name="N° Registro")
    def __str__(self):
        return self.nombre + " " + self.apellido
    class Meta:
        verbose_name = "Voluntario"
        verbose_name_plural = "Voluntarios"

class Contacto(models.Model):
    nombre  = models.CharField(max_length=75, null=False, blank=False, help_text="Ingresa tu nombre completo", validators=[validar_mensaje])
    correo  = models.EmailField(max_length=50, null=False, blank=False, help_text="Ingresa tu correo electrónico", validators=[validar_dominio_correo])
    asunto  = models.CharField(max_length=50, null=False, blank=False, help_text="Ingresa el motivo por el cual nos contacta", validators=[validar_mensaje])
    mensaje = models.CharField(max_length=500, null=False, blank=False, help_text="Coméntanos en que te podemos ayudar (máximo de 500 caracteres)", validators=[validar_mensaje])
    def __str__(self):
        return "Mensaje de" + self.nombre
    class Meta:
        verbose_name = "Recepción - contacto"
        verbose_name_plural = "Recepción - contactos"

class Postulacion(models.Model):
    nombre = models.CharField(max_length=50, null=False, blank=False, help_text="Ingresa tu nombre completo", validators=[validar_mensaje])
    correo = models.EmailField(max_length=50, null=False, blank=False, help_text="Ingresa tu correo electrónico", validators=[validar_dominio_correo])
    telefono = models.CharField(max_length=8, null=False, blank=False, help_text="Ingresa tu número de teléfono. No ingresar +56 9", verbose_name="Teléfono", validators=[validar_telefono])
    formulario = models.FileField(max_length=100, null=False, upload_to="postulaciones", help_text="Sube tu formulario en formato PDF", validators=[validar_formato_pdf, validar_tamano_pdf])

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = "Postulación"
        verbose_name_plural = "Postulaciones"
       
class Galeria(models.Model):
    titulo      = models.CharField(max_length=50, null=True, blank=True, help_text="Suba la imagen", verbose_name="Título", validators=[validar_mensaje])
    descripcion = models.CharField(max_length=60, null=True, blank=True, help_text="Ingresa una descripcion", verbose_name="Descripción", validators=[validar_mensaje])
    imagen      = models.ImageField(max_length=50, null=True, upload_to="Galeria", validators=[validar_formato_imagen,validar_tamano_imagen])
    def __str__(self):
        return self.titulo
    class Meta:
        verbose_name = "Galería - imagen"
        verbose_name_plural = "Galería - imágenes"
    

apps/webpage/forms.py
from multiprocessing import Value
from django import forms
from django.core.exceptions import ValidationError
from .models import (CategoriaNoticia, Noticia, Contenido, EspecialidadCarro, CarroBomba, 
                     CargoMiembro, Miembro, Contacto, Postulacion, Galeria)
from django.core.exceptions import ValidationError
import re 

# Formulario para CategoriaNoticia
class CategoriaNoticiaForm(forms.ModelForm):
    class Meta:
        model = CategoriaNoticia
        fields = '__all__'
    def clean(self):
        cleaned_data = super().clean()
        # Aquí puedes agregar validaciones que involucren varios campos
        return cleaned_data

# Formulario para Noticia
class NoticiaForm(forms.ModelForm):
    class Meta:
        model = Noticia
        fields = '__all__'
    def clean(self):
        cleaned_data = super().clean()
        # Aquí puedes agregar validaciones que involucren varios campos
        return cleaned_data

# Formulario para Contenido
class ContenidoForm(forms.ModelForm):
    class Meta:
        model = Contenido
        fields = '__all__'
    def clean(self):
        cleaned_data = super().clean()
        # Aquí puedes agregar validaciones que involucren varios campos
        return cleaned_data

# Formulario para especialidad del carro
class EspecialidadCarroForm(forms.ModelForm):
    class Meta:
        model = EspecialidadCarro
        fields = '__all__'
    def clean(self):
        cleaned_data = super().clean()
        # Aquí puedes agregar validaciones que involucren varios campos
        return cleaned_data

# Formulario para el carro
class CarroBombaForm(forms.ModelForm):
    class Meta:
        model = CarroBomba
        fields = '__all__'
    def clean(self):
        cleaned_data = super().clean()
        # Aquí puedes agregar validaciones que involucren varios campos
        return cleaned_data
        
# Formulario para el cargo del miembro
class CargoMiembroForm(forms.ModelForm):
    class Meta:
        model = CargoMiembro
        fields = '__all__'
    def clean(self):
        cleaned_data = super().clean()
        # Aquí puedes agregar validaciones que involucren varios campos
        return cleaned_data

# Formulario para el miembro
class MiembroForm(forms.ModelForm):
    class Meta:
        model = Miembro
        fields = '__all__'
    def clean(self):
        cleaned_data = super().clean()
        # Aquí puedes agregar validaciones que involucren varios campos
        return cleaned_data

# Formulario para el contacto
class ContactoForm(forms.ModelForm):
    class Meta:
        model = Contacto
        fields = '__all__'
    def clean(self):
        cleaned_data = super().clean()
        return cleaned_data
    #NOMBRE
    def validar_mensaje(value):
    # Verifica si contiene palabras inapropiadas
        PALABRAS_INAPROPIADAS = ['Mierda', 'Puta', 'Conchetumare', 'conchetumare', 'Ctm', 'ctm', 'maricon', 'marica']
        if any(palabra in value.lower() for palabra in PALABRAS_INAPROPIADAS):
            raise ValidationError('El mensaje contiene lenguaje inapropiado.')
    # Mensaje
    def clean_mensaje(self):
        mensaje = self.cleaned_data['mensaje']
        palabras_inapropiadas = ['Mierda', 'Puta', 'Conchetumare', 'conchetumare', 'Ctm', 'ctm', 'maricon', 'marica']
        
        if any(palabra in mensaje.lower() for palabra in palabras_inapropiadas):
            raise ValidationError('El mensaje contiene lenguaje inapropiado.')

        if re.search(r'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*(),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+', mensaje):
            raise ValidationError('El mensaje no debe contener URLs.')
        return mensaje

    def clean_correo(self):
        correo = self.cleaned_data['correo']
        dominios_permitidos = ['gmail.com', 'primeracbpa.cl', 'icloud.com', 'cbpa.cl', 'duocuc.cl', 'outlook.es', 'outlook.com', 'outlook.cl']
        dominio_email = correo.split('@')[-1]

        if dominio_email not in dominios_permitidos:
            raise ValidationError('El dominio del correo electrónico no está permitido.')
        return correo

# Formulario para la postulacion
class PostulacionForm(forms.ModelForm):
    class Meta:
        model = Postulacion
        fields = '__all__'
    def clean(self):
        cleaned_data = super().clean()
        # Aquí puedes agregar validaciones que involucren varios campos
        formulario = self.cleaned_data.get('formulario')

        # Validación del tamaño del archivo
        max_size = 10 * 1024 * 1024  # 10 MB
        if formulario.size > max_size:
            raise ValidationError('El tamaño del archivo no puede exceder los 10 MB.')

        # Validación de la extensión del archivo
        if not formulario.name.endswith('.pdf'):
            raise ValidationError('El archivo debe ser un PDF.')
        return cleaned_data

# Formulario para el contacto
class GaleriaForm(forms.ModelForm):
    class Meta:
        model = Galeria
        fields = '__all__'
    def clean(self):
        cleaned_data = super().clean()
        # Aquí puedes agregar validaciones que involucren varios campos
        return cleaned_data

templates/webpage/noticias.html
{% extends "webpage_base.html" %}
{% load static%}
{% block titulo %}{{ name_hero }}{% endblock%}
{% block content %}
<!-- Start: Hero -->
<section class="py-5 text-white bg-primary text-center mb-4" style="background-image: url('{% static 'img/hero-default-img.svg' %}'); background-position: center; background-size: cover;">
    <div class="container">
        <h1 class="text-uppercase fw-semibold mb-3">{{ name_hero }}</h1>
        <!--<p class="mb-4">{{ description_hero }}</p>-->
    </div>
</section>
<!-- Start: Noticias -->
<section data-aos="fade-up" style="margin-bottom: 32px;">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <h3 class="text-capitalize text-primary text-opacity-75">Todos</h3>
                <p>Aquí aparecerán los últimos artículos de nuestra compañía</p>
            </div>
        </div>
        <form class="py-4 py-xl-5 border rounded border-0 border-light d-flex flex-column align-items-center p-4 p-md-5" method="get" action="{% url 'noticias' %}">
            <div class="d-flex align-items-center justify-content-center justify-content-md-start flex-wrap">
                <label for="fecha_filtro" class="text-primary pb-2 pb-lg-1 me-md-2">Filtrar por fecha:</label>
                <select name="fecha_filtro" id="fecha_filtro" class="form-select me-md-2" style="width: 200px;">
                    <option value="" {% if not fecha_filtro %}selected{% endif %}>Todas las fechas</option>
                    <option value="hoy" {% if fecha_filtro == 'hoy' %}selected{% endif %}>Hoy</option>
                    <option value="semana" {% if fecha_filtro == 'semana' %}selected{% endif %}>Última semana</option>
                </select>
                <button type="submit" class="btn btn-primary py-2 px-4" style="background-color: transparent; border: 2px solid var(--bs-primary);">Filtrar</button>
            </div>
        </form>
        <div class="row gy-4 row-cols-1 row-cols-md-2 row-cols-xl-3">
            {% if user.is_authenticated %}
            <div class="col">
                <a href="{% url 'admin:webpage_noticia_changelist' %}" style="color: var(--bs-body-bg);">
                    <div class="card border-secondary-subtle">
                        <img class="card-img-top w-100 d-block card-img-top w-100 fit-cover"
                             style="height:200px;"
                             src="{% static 'img/default-user.png' %}">
                        <div class="card-body p-4">
                            <p class="text-primary card-text">¿Deseas agregar una noticia?</p>
                            <h4 class="card-title">Presióname</h4>
                            <p class="card-text"></p>
                            <div class="d-flex">
                                <div>
                                    <p class="fw-bold mb-0"></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            {% endif %}
            {% for noticia in noticias %}
            <div class="col">
                <div class="card border-secondary-subtle">
                    <img class="card-img-top w-100 d-block card-img-top w-100 fit-cover"
                         style="height:200px;"
                         src="{{ noticia.imagen_noticia.url }}">
                    <div class="card-body p-4">
                        <p class="text-primary card-text">{{ noticia.categoria.CategoriaNoticia }}</p>
                        <h4 class="card-title">{{ noticia.titulo }}</h4>
                        <p class="card-text">
                            {% for contenido in noticia.contenido_set.all %}
                            {{ contenido.contenido|truncatechars:20 }}
                            {% endfor %}
                        </p>
                        <div class="d-flex justify-content-between align-items-center">
                            <p class="fw-bold mb-0">{{ noticia.fecha_pub|date:"d M Y" }}</p>
                            <button type="button" class="btn btn-primary ver-detalle" data-bs-toggle="modal" data-bs-target="#noticiaModal" data-noticia-id="{{ noticia.id }}">
                              Ver Detalles
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="col">
                <a href="#" style="color: var(--bs-body-bg);">
                    <div class="card border-secondary-subtle">
                        <img class="card-img-top w-100 d-block card-img-top w-100 fit-cover"
                             style="height:200px;"
                             src="{% static 'img/default-user.png' %}">
                        <div class="card-body p-4">
                            <p class="text-primary card-text">No disponible</p>
                            <h4 class="card-title">No disponible</h4>
                            <p class="card-text">No disponible</p>
                            <div class="d-flex">
                                <div>
                                    <p class="fw-bold mb-0">No disponible</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
<!-- Start: Historia -->
<section id="Historia" data-aos="fade-up" style="margin-bottom: 32px;">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <h3 class="text-capitalize text-primary text-opacity-75">Historia</h3>
                <p>Aquí encontrarás las últimas publicaciones de nuestro historiador.</p>
            </div>
        </div>
        <div class="row gy-4 row-cols-1 row-cols-md-2 row-cols-xl-3">
            {% for noticia in noticias_historia %}
            <div class="col">
                <div class="card border-secondary-subtle">
                    <img class="card-img-top w-100 d-block card-img-top w-100 fit-cover" style="height:200px;" src="{{ noticia.imagen_noticia.url }}">
                    <div class="card-body p-4">
                        <p class="text-primary card-text">{{ noticia.categoria.CategoriaNoticia }}</p>
                        <h4 class="card-title">{{ noticia.titulo }}</h4>
                        <p class="card-text">
                            {% for contenido in noticia.contenido_set.all %}
                            {{ contenido.contenido|truncatechars:20 }}
                            {% endfor %}
                        </p>
                        <div class="d-flex justify-content-between align-items-center">
                            <p class="fw-bold mb-0">{{ noticia.fecha_pub|date:"d M Y" }}</p>
                            <button type="button" class="btn btn-primary ver-detalle" data-bs-toggle="modal" data-bs-target="#noticiaModal" data-noticia-id="{{ noticia.id }}">
                              Ver Detalles
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="col">
                <a href="#" style="color: var(--bs-body-bg);">
                    <div class="card border-secondary-subtle">
                        <img class="card-img-top w-100 d-block card-img-top w-100 fit-cover" style="height:200px;" src="{% static 'img/default-user.png' %}">
                        <div class="card-body p-4">
                            <p class="text-primary card-text">No disponible</p>
                            <h4 class="card-title">No disponible</h4>
                            <p class="card-text">No disponible</p>
                            <div class="d-flex">
                                <div>
                                    <p class="fw-bold mb-0">No disponible</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
<!-- Start: Tips para la comunidad -->
<section data-aos="fade-up" style="margin-bottom: 32px;">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <h3 class="text-primary text-opacity-75">Ayuda a la comunidad</h3>
                <p>Aquí aparecerán los últimos artículos sobre tips para la comunidad</p>
            </div>
        </div>
        <div class="row gy-4 row-cols-1 row-cols-md-2 row-cols-xl-3">
            {% for noticia in noticias_comunidad %}
            <div class="col">
                <div class="card border-secondary-subtle">
                    <img class="card-img-top w-100 fit-cover" style="height:200px;" src="{{ noticia.imagen_noticia.url }}" alt="{{ noticia.titulo }}">
                    <div class="card-body p-4">
                        <p class="text-primary card-text">{{ noticia.categoria.CategoriaNoticia }}</p>
                        <h4 class="card-title">{{ noticia.titulo }}</h4>
                        <p class="card-text">
                            {% for contenido in noticia.contenido_set.all %}
                            {{ contenido.contenido|truncatechars:20 }}
                            {% endfor %}
                        </p>
                        <div class="d-flex justify-content-between align-items-center">
                            <p class="fw-bold mb-0">{{ noticia.fecha_pub|date:"d M Y" }}</p>
                            <button type="button" class="btn btn-primary ver-detalle" data-bs-toggle="modal" data-bs-target="#noticiaModal" data-noticia-id="{{ noticia.id }}">
                              Ver Detalles
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="col">
                <a href="#" style="color: var(--bs-body-bg);">
                    <div class="card border-secondary-subtle">
                        <img class="card-img-top w-100 fit-cover" style="height:200px;" src="{% static 'img/default-user.png' %}" alt="No Disponible">
                        <div class="card-body p-4">
                            <p class="text-primary card-text">No disponible</p>
                            <h4 class="card-title">No disponible</h4>
                            <p class="card-text">No disponible</p>
                            <div class="d-flex">
                                <div>
                                    <p class="fw-bold mb-0">No disponible</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
<!--Ventana modal para mostrar el detalle-->
<div class="modal fade" id="noticiaModal" tabindex="-1" aria-labelledby="noticiaModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="noticiaModalLabel">De   talle de la Noticia</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-6">
                            <img class="img-fluid" id="noticiaModalImage" alt="Imagen de la noticia">
                        </div>
                        <div class="col-lg-6">
                            <h2 id="noticiaModalTitle"></h2>
                            <p class="text-primary" id="noticiaModalCategory"></p>
                            <p id="noticiaModalDate"></p>
                            <div id="noticiaModalContent"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock%}

{% block js %}
<!--Más codigo para las noticias-->
<script>
    document.addEventListener('DOMContentLoaded', function () {
        var verDetalleButtons = document.querySelectorAll('.ver-detalle');
    
        verDetalleButtons.forEach(function (btn) {
          btn.addEventListener('click', function () {
            var noticiaId = this.getAttribute('data-noticia-id');
            
            // Realizar solicitud AJAX
            fetch('/ruta-a-tu-vista-detalle-noticia/' + noticiaId)
              .then(response => response.text())
              .then(data => {
                document.querySelector('#noticiaModal .modal-body').innerHTML = data;
              });
          });
        });
    }); 
</script>
{% endblock%}